#pragma managed(push, off)

#include "../../Includes.h"
#include "../../GlIncludes.h"

#define DLL_EXPORT __declspec(dllexport)

#define WRAP_RAYLIB_FUNC(func_name, ret_type, arg_types, arg_names) \
DLL_EXPORT ret_type RL_##func_name arg_types {                      \
    return func_name arg_names;                                     \
}

#define WRAP_RAYLIB_FUNC_NO_ARGS(func_name, ret_type) \
DLL_EXPORT ret_type RL_##func_name() {                \
    return func_name();                               \
}


using namespace RAYLIB;

extern "C"
{
#pragma region EXPORTS

    WRAP_RAYLIB_FUNC(InitWindow, void, (int width, int height, const char* title), (width, height, title))
    WRAP_RAYLIB_FUNC_NO_ARGS(CloseWindow, void)
    WRAP_RAYLIB_FUNC_NO_ARGS(WindowShouldClose, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowReady, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowFullscreen, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowHidden, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowMinimized, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowMaximized, bool)
    WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowFocused, bool)
        WRAP_RAYLIB_FUNC_NO_ARGS(IsWindowResized, bool)
        WRAP_RAYLIB_FUNC(IsWindowState, bool, (unsigned int flag), (flag))
        WRAP_RAYLIB_FUNC(SetWindowState, void, (unsigned int flags), (flags))
        WRAP_RAYLIB_FUNC(ClearWindowState, void, (unsigned int flags), (flags))
        WRAP_RAYLIB_FUNC_NO_ARGS(ToggleFullscreen, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(ToggleBorderlessWindowed, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(MaximizeWindow, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(MinimizeWindow, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(RestoreWindow, void)
        WRAP_RAYLIB_FUNC(SetWindowIcon, void, (Image image), (image))
        WRAP_RAYLIB_FUNC(SetWindowIcons, void, (Image* images, int count), (images, count))
        WRAP_RAYLIB_FUNC(SetWindowTitle, void, (const char* title), (title))
        WRAP_RAYLIB_FUNC(SetWindowPosition, void, (int x, int y), (x, y))
        WRAP_RAYLIB_FUNC(SetWindowMonitor, void, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(SetWindowMinSize, void, (int width, int height), (width, height))
        WRAP_RAYLIB_FUNC(SetWindowMaxSize, void, (int width, int height), (width, height))
        WRAP_RAYLIB_FUNC(SetWindowSize, void, (int width, int height), (width, height))
        WRAP_RAYLIB_FUNC(SetWindowOpacity, void, (float opacity), (opacity))
        WRAP_RAYLIB_FUNC_NO_ARGS(SetWindowFocused, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetScreenWidth, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetScreenHeight, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetRenderWidth, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetRenderHeight, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMonitorCount, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetCurrentMonitor, int)
        WRAP_RAYLIB_FUNC(GetMonitorPosition, Vector2, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(GetMonitorWidth, int, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(GetMonitorHeight, int, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(GetMonitorPhysicalWidth, int, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(GetMonitorPhysicalHeight, int, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC(GetMonitorRefreshRate, int, (int monitor), (monitor))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetWindowPosition, Vector2)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetWindowScaleDPI, Vector2)
        WRAP_RAYLIB_FUNC(SetClipboardText, void, (const char* text), (text))
        WRAP_RAYLIB_FUNC_NO_ARGS(EnableEventWaiting, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(DisableEventWaiting, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(ShowCursor, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(HideCursor, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(IsCursorHidden, bool)
        WRAP_RAYLIB_FUNC_NO_ARGS(EnableCursor, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(DisableCursor, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(IsCursorOnScreen, bool)
        WRAP_RAYLIB_FUNC(ClearBackground, void, (Color color), (color))
        WRAP_RAYLIB_FUNC_NO_ARGS(BeginDrawing, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(EndDrawing, void)
        WRAP_RAYLIB_FUNC(BeginMode2D, void, (Camera2D camera), (camera))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndMode2D, void)
        WRAP_RAYLIB_FUNC(BeginMode3D, void, (Camera3D camera), (camera))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndMode3D, void)
        WRAP_RAYLIB_FUNC(BeginTextureMode, void, (RenderTexture2D target), (target))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndTextureMode, void)
        WRAP_RAYLIB_FUNC(BeginShaderMode, void, (Shader shader), (shader))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndShaderMode, void)
        WRAP_RAYLIB_FUNC(BeginBlendMode, void, (int mode), (mode))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndBlendMode, void)
        WRAP_RAYLIB_FUNC(BeginScissorMode, void, (int x, int y, int width, int height), (x, y, width, height))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndScissorMode, void)
        WRAP_RAYLIB_FUNC(BeginVrStereoMode, void, (VrStereoConfig config), (config))
        WRAP_RAYLIB_FUNC_NO_ARGS(EndVrStereoMode, void)
        WRAP_RAYLIB_FUNC(LoadVrStereoConfig, VrStereoConfig, (VrDeviceInfo device), (device))
        WRAP_RAYLIB_FUNC(UnloadVrStereoConfig, void, (VrStereoConfig config), (config))
        WRAP_RAYLIB_FUNC(LoadShader, Shader, (const char* vsFileName, const char* fsFileName), (vsFileName, fsFileName))
        WRAP_RAYLIB_FUNC(LoadShaderFromMemory, Shader, (const char* vsCode, const char* fsCode), (vsCode, fsCode))
        WRAP_RAYLIB_FUNC(IsShaderReady, bool, (Shader shader), (shader))
        WRAP_RAYLIB_FUNC(GetShaderLocation, int, (Shader shader, const char* uniformName), (shader, uniformName))
        WRAP_RAYLIB_FUNC(GetShaderLocationAttrib, int, (Shader shader, const char* attribName), (shader, attribName))
        WRAP_RAYLIB_FUNC(SetShaderValue, void, (Shader shader, int locIndex, const void* value, int uniformType), (shader, locIndex, value, uniformType))
        WRAP_RAYLIB_FUNC(SetShaderValueV, void, (Shader shader, int locIndex, const void* value, int uniformType, int count), (shader, locIndex, value, uniformType, count))
        WRAP_RAYLIB_FUNC(SetShaderValueMatrix, void, (Shader shader, int locIndex, Matrix mat), (shader, locIndex, mat))
        WRAP_RAYLIB_FUNC(SetShaderValueTexture, void, (Shader shader, int locIndex, Texture2D texture), (shader, locIndex, texture))
        WRAP_RAYLIB_FUNC(UnloadShader, void, (Shader shader), (shader))
        WRAP_RAYLIB_FUNC(GetScreenToWorldRay, Ray, (Vector2 position, Camera camera), (position, camera))
        WRAP_RAYLIB_FUNC(GetScreenToWorldRayEx, Ray, (Vector2 position, Camera camera, int width, int height), (position, camera, width, height))
        WRAP_RAYLIB_FUNC(GetWorldToScreen, Vector2, (Vector3 position, Camera camera), (position, camera))
        WRAP_RAYLIB_FUNC(GetWorldToScreenEx, Vector2, (Vector3 position, Camera camera, int width, int height), (position, camera, width, height))
        WRAP_RAYLIB_FUNC(GetWorldToScreen2D, Vector2, (Vector2 position, Camera2D camera), (position, camera))
        WRAP_RAYLIB_FUNC(GetScreenToWorld2D, Vector2, (Vector2 position, Camera2D camera), (position, camera))
        WRAP_RAYLIB_FUNC(GetCameraMatrix, Matrix, (Camera camera), (camera))
        WRAP_RAYLIB_FUNC(GetCameraMatrix2D, Matrix, (Camera2D camera), (camera))
        WRAP_RAYLIB_FUNC(SetTargetFPS, void, (int fps), (fps))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetFrameTime, float)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetTime, double)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetFPS, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(SwapScreenBuffer, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(PollInputEvents, void)
        WRAP_RAYLIB_FUNC(WaitTime, void, (double seconds), (seconds))
        WRAP_RAYLIB_FUNC(SetRandomSeed, void, (unsigned int seed), (seed))
        WRAP_RAYLIB_FUNC(GetRandomValue, int, (int min, int max), (min, max))
        WRAP_RAYLIB_FUNC(UnloadRandomSequence, void, (int* sequence), (sequence))
        WRAP_RAYLIB_FUNC(TakeScreenshot, void, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(SetConfigFlags, void, (unsigned int flags), (flags))
        WRAP_RAYLIB_FUNC(OpenURL, void, (const char* url), (url))
        WRAP_RAYLIB_FUNC(TraceLog, void, (int logLevel, const char* text, ...), (logLevel, text))
        WRAP_RAYLIB_FUNC(SetTraceLogLevel, void, (int logLevel), (logLevel))
        WRAP_RAYLIB_FUNC(MemFree, void, (void* ptr), (ptr))
        WRAP_RAYLIB_FUNC(SetTraceLogCallback, void, (TraceLogCallback callback), (callback))
        WRAP_RAYLIB_FUNC(SetLoadFileDataCallback, void, (LoadFileDataCallback callback), (callback))
        WRAP_RAYLIB_FUNC(SetSaveFileDataCallback, void, (SaveFileDataCallback callback), (callback))
        WRAP_RAYLIB_FUNC(SetLoadFileTextCallback, void, (LoadFileTextCallback callback), (callback))
        WRAP_RAYLIB_FUNC(SetSaveFileTextCallback, void, (SaveFileTextCallback callback), (callback))
        WRAP_RAYLIB_FUNC(UnloadFileData, void, (unsigned char* data), (data))
        WRAP_RAYLIB_FUNC(SaveFileData, bool, (const char* fileName, void* data, int dataSize), (fileName, data, dataSize))
        WRAP_RAYLIB_FUNC(ExportDataAsCode, bool, (const unsigned char* data, int dataSize, const char* fileName), (data, dataSize, fileName))
        WRAP_RAYLIB_FUNC(UnloadFileText, void, (char* text), (text))
        WRAP_RAYLIB_FUNC(SaveFileText, bool, (const char* fileName, char* text), (fileName, text))
        WRAP_RAYLIB_FUNC(FileExists, bool, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(DirectoryExists, bool, (const char* dirPath), (dirPath))
        WRAP_RAYLIB_FUNC(IsFileExtension, bool, (const char* fileName, const char* ext), (fileName, ext))
        WRAP_RAYLIB_FUNC(GetFileLength, int, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(ChangeDirectory, bool, (const char* dir), (dir))
        WRAP_RAYLIB_FUNC(IsPathFile, bool, (const char* path), (path))
        WRAP_RAYLIB_FUNC(IsFileNameValid, bool, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadDirectoryFiles, FilePathList, (const char* dirPath), (dirPath))
        WRAP_RAYLIB_FUNC(LoadDirectoryFilesEx, FilePathList, (const char* basePath, const char* filter, bool scanSubdirs), (basePath, filter, scanSubdirs))
        WRAP_RAYLIB_FUNC(UnloadDirectoryFiles, void, (FilePathList files), (files))
        WRAP_RAYLIB_FUNC_NO_ARGS(IsFileDropped, bool)
        WRAP_RAYLIB_FUNC_NO_ARGS(LoadDroppedFiles, FilePathList)
        WRAP_RAYLIB_FUNC(UnloadDroppedFiles, void, (FilePathList files), (files))
        WRAP_RAYLIB_FUNC(GetFileModTime, long, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadAutomationEventList, AutomationEventList, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(UnloadAutomationEventList, void, (AutomationEventList list), (list))
        WRAP_RAYLIB_FUNC(ExportAutomationEventList, bool, (AutomationEventList list, const char* fileName), (list, fileName))
        WRAP_RAYLIB_FUNC(SetAutomationEventList, void, (AutomationEventList* list), (list))
        WRAP_RAYLIB_FUNC(SetAutomationEventBaseFrame, void, (int frame), (frame))
        WRAP_RAYLIB_FUNC_NO_ARGS(StartAutomationEventRecording, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(StopAutomationEventRecording, void)
        WRAP_RAYLIB_FUNC(PlayAutomationEvent, void, (AutomationEvent event), (event))
        WRAP_RAYLIB_FUNC(IsKeyPressed, bool, (int key), (key))
        WRAP_RAYLIB_FUNC(IsKeyPressedRepeat, bool, (int key), (key))
        WRAP_RAYLIB_FUNC(IsKeyDown, bool, (int key), (key))
        WRAP_RAYLIB_FUNC(IsKeyReleased, bool, (int key), (key))
        WRAP_RAYLIB_FUNC(IsKeyUp, bool, (int key), (key))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetKeyPressed, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetCharPressed, int)
        WRAP_RAYLIB_FUNC(SetExitKey, void, (int key), (key))
        WRAP_RAYLIB_FUNC(IsGamepadAvailable, bool, (int gamepad), (gamepad))
        WRAP_RAYLIB_FUNC(IsGamepadButtonPressed, bool, (int gamepad, int button), (gamepad, button))
        WRAP_RAYLIB_FUNC(IsGamepadButtonDown, bool, (int gamepad, int button), (gamepad, button))
        WRAP_RAYLIB_FUNC(IsGamepadButtonReleased, bool, (int gamepad, int button), (gamepad, button))
        WRAP_RAYLIB_FUNC(IsGamepadButtonUp, bool, (int gamepad, int button), (gamepad, button))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGamepadButtonPressed, int)
        WRAP_RAYLIB_FUNC(GetGamepadAxisCount, int, (int gamepad), (gamepad))
        WRAP_RAYLIB_FUNC(GetGamepadAxisMovement, float, (int gamepad, int axis), (gamepad, axis))
        WRAP_RAYLIB_FUNC(SetGamepadMappings, int, (const char* mappings), (mappings))
        WRAP_RAYLIB_FUNC(SetGamepadVibration, void, (int gamepad, float leftMotor, float rightMotor), (gamepad, leftMotor, rightMotor))
        WRAP_RAYLIB_FUNC(IsMouseButtonPressed, bool, (int button), (button))
        WRAP_RAYLIB_FUNC(IsMouseButtonDown, bool, (int button), (button))
        WRAP_RAYLIB_FUNC(IsMouseButtonReleased, bool, (int button), (button))
        WRAP_RAYLIB_FUNC(IsMouseButtonUp, bool, (int button), (button))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMouseX, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMouseY, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMousePosition, Vector2)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMouseDelta, Vector2)
        WRAP_RAYLIB_FUNC(SetMousePosition, void, (int x, int y), (x, y))
        WRAP_RAYLIB_FUNC(SetMouseOffset, void, (int offsetX, int offsetY), (offsetX, offsetY))
        WRAP_RAYLIB_FUNC(SetMouseScale, void, (float scaleX, float scaleY), (scaleX, scaleY))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMouseWheelMove, float)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMouseWheelMoveV, Vector2)
        WRAP_RAYLIB_FUNC(SetMouseCursor, void, (int cursor), (cursor))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetTouchX, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetTouchY, int)
        WRAP_RAYLIB_FUNC(GetTouchPosition, Vector2, (int index), (index))
        WRAP_RAYLIB_FUNC(GetTouchPointId, int, (int index), (index))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetTouchPointCount, int)
        WRAP_RAYLIB_FUNC(SetGesturesEnabled, void, (unsigned int flags), (flags))
        WRAP_RAYLIB_FUNC(IsGestureDetected, bool, (unsigned int gesture), (gesture))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGestureDetected, int)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGestureHoldDuration, float)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGestureDragVector, Vector2)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGestureDragAngle, float)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGesturePinchVector, Vector2)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetGesturePinchAngle, float)
        WRAP_RAYLIB_FUNC(UpdateCamera, void, (Camera* camera, int mode), (camera, mode))
        WRAP_RAYLIB_FUNC(UpdateCameraPro, void, (Camera* camera, Vector3 movement, Vector3 rotation, float zoom), (camera, movement, rotation, zoom))
        WRAP_RAYLIB_FUNC(SetShapesTexture, void, (Texture2D texture, Rectangle source), (texture, source))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetShapesTexture, Texture2D)
        WRAP_RAYLIB_FUNC_NO_ARGS(GetShapesTextureRectangle, Rectangle)
        WRAP_RAYLIB_FUNC(DrawPixel, void, (int posX, int posY, Color color), (posX, posY, color))
        WRAP_RAYLIB_FUNC(DrawPixelV, void, (Vector2 position, Color color), (position, color))
        WRAP_RAYLIB_FUNC(DrawLine, void, (int startPosX, int startPosY, int endPosX, int endPosY, Color color), (startPosX, startPosY, endPosX, endPosY, color))
        WRAP_RAYLIB_FUNC(DrawLineV, void, (Vector2 startPos, Vector2 endPos, Color color), (startPos, endPos, color))
        WRAP_RAYLIB_FUNC(DrawLineEx, void, (Vector2 startPos, Vector2 endPos, float thick, Color color), (startPos, endPos, thick, color))
        WRAP_RAYLIB_FUNC(DrawLineStrip, void, (const Vector2* points, int pointCount, Color color), (points, pointCount, color))
        WRAP_RAYLIB_FUNC(DrawLineBezier, void, (Vector2 startPos, Vector2 endPos, float thick, Color color), (startPos, endPos, thick, color))
        WRAP_RAYLIB_FUNC(DrawCircle, void, (int centerX, int centerY, float radius, Color color), (centerX, centerY, radius, color))
        WRAP_RAYLIB_FUNC(DrawCircleSector, void, (Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color), (center, radius, startAngle, endAngle, segments, color))
        WRAP_RAYLIB_FUNC(DrawCircleSectorLines, void, (Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color), (center, radius, startAngle, endAngle, segments, color))
        WRAP_RAYLIB_FUNC(DrawCircleGradient, void, (int centerX, int centerY, float radius, Color inner, Color outer), (centerX, centerY, radius, inner, outer))
        WRAP_RAYLIB_FUNC(DrawCircleV, void, (Vector2 center, float radius, Color color), (center, radius, color))
        WRAP_RAYLIB_FUNC(DrawCircleLines, void, (int centerX, int centerY, float radius, Color color), (centerX, centerY, radius, color))
        WRAP_RAYLIB_FUNC(DrawCircleLinesV, void, (Vector2 center, float radius, Color color), (center, radius, color))
        WRAP_RAYLIB_FUNC(DrawEllipse, void, (int centerX, int centerY, float radiusH, float radiusV, Color color), (centerX, centerY, radiusH, radiusV, color))
        WRAP_RAYLIB_FUNC(DrawEllipseLines, void, (int centerX, int centerY, float radiusH, float radiusV, Color color), (centerX, centerY, radiusH, radiusV, color))
        WRAP_RAYLIB_FUNC(DrawRing, void, (Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color), (center, innerRadius, outerRadius, startAngle, endAngle, segments, color))
        WRAP_RAYLIB_FUNC(DrawRingLines, void, (Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color), (center, innerRadius, outerRadius, startAngle, endAngle, segments, color))
        WRAP_RAYLIB_FUNC(DrawRectangle, void, (int posX, int posY, int width, int height, Color color), (posX, posY, width, height, color))
        WRAP_RAYLIB_FUNC(DrawRectangleV, void, (Vector2 position, Vector2 size, Color color), (position, size, color))
        WRAP_RAYLIB_FUNC(DrawRectangleRec, void, (Rectangle rec, Color color), (rec, color))
        WRAP_RAYLIB_FUNC(DrawRectanglePro, void, (Rectangle rec, Vector2 origin, float rotation, Color color), (rec, origin, rotation, color))
        WRAP_RAYLIB_FUNC(DrawRectangleGradientV, void, (int posX, int posY, int width, int height, Color top, Color bottom), (posX, posY, width, height, top, bottom))
        WRAP_RAYLIB_FUNC(DrawRectangleGradientH, void, (int posX, int posY, int width, int height, Color left, Color right), (posX, posY, width, height, left, right))
        WRAP_RAYLIB_FUNC(DrawRectangleGradientEx, void, (Rectangle rec, Color topLeft, Color bottomLeft, Color topRight, Color bottomRight), (rec, topLeft, bottomLeft, topRight, bottomRight))
        WRAP_RAYLIB_FUNC(DrawRectangleLines, void, (int posX, int posY, int width, int height, Color color), (posX, posY, width, height, color))
        WRAP_RAYLIB_FUNC(DrawRectangleLinesEx, void, (Rectangle rec, float lineThick, Color color), (rec, lineThick, color))
        WRAP_RAYLIB_FUNC(DrawRectangleRounded, void, (Rectangle rec, float roundness, int segments, Color color), (rec, roundness, segments, color))
        WRAP_RAYLIB_FUNC(DrawRectangleRoundedLines, void, (Rectangle rec, float roundness, int segments, Color color), (rec, roundness, segments, color))
        WRAP_RAYLIB_FUNC(DrawRectangleRoundedLinesEx, void, (Rectangle rec, float roundness, int segments, float lineThick, Color color), (rec, roundness, segments, lineThick, color))
        WRAP_RAYLIB_FUNC(DrawTriangle, void, (Vector2 v1, Vector2 v2, Vector2 v3, Color color), (v1, v2, v3, color))
        WRAP_RAYLIB_FUNC(DrawTriangleLines, void, (Vector2 v1, Vector2 v2, Vector2 v3, Color color), (v1, v2, v3, color))
        WRAP_RAYLIB_FUNC(DrawTriangleFan, void, (const Vector2* points, int pointCount, Color color), (points, pointCount, color))
        WRAP_RAYLIB_FUNC(DrawTriangleStrip, void, (const Vector2* points, int pointCount, Color color), (points, pointCount, color))
        WRAP_RAYLIB_FUNC(DrawPoly, void, (Vector2 center, int sides, float radius, float rotation, Color color), (center, sides, radius, rotation, color))
        WRAP_RAYLIB_FUNC(DrawPolyLines, void, (Vector2 center, int sides, float radius, float rotation, Color color), (center, sides, radius, rotation, color))
        WRAP_RAYLIB_FUNC(DrawPolyLinesEx, void, (Vector2 center, int sides, float radius, float rotation, float lineThick, Color color), (center, sides, radius, rotation, lineThick, color))
        WRAP_RAYLIB_FUNC(DrawSplineLinear, void, (const Vector2* points, int pointCount, float thick, Color color), (points, pointCount, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineBasis, void, (const Vector2* points, int pointCount, float thick, Color color), (points, pointCount, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineCatmullRom, void, (const Vector2* points, int pointCount, float thick, Color color), (points, pointCount, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineBezierQuadratic, void, (const Vector2* points, int pointCount, float thick, Color color), (points, pointCount, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineBezierCubic, void, (const Vector2* points, int pointCount, float thick, Color color), (points, pointCount, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineSegmentLinear, void, (Vector2 p1, Vector2 p2, float thick, Color color), (p1, p2, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineSegmentBasis, void, (Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color), (p1, p2, p3, p4, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineSegmentCatmullRom, void, (Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color), (p1, p2, p3, p4, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineSegmentBezierQuadratic, void, (Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color), (p1, c2, p3, thick, color))
        WRAP_RAYLIB_FUNC(DrawSplineSegmentBezierCubic, void, (Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color), (p1, c2, c3, p4, thick, color))
        WRAP_RAYLIB_FUNC(GetSplinePointLinear, Vector2, (Vector2 startPos, Vector2 endPos, float t), (startPos, endPos, t))
        WRAP_RAYLIB_FUNC(GetSplinePointBasis, Vector2, (Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t), (p1, p2, p3, p4, t))
        WRAP_RAYLIB_FUNC(GetSplinePointCatmullRom, Vector2, (Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t), (p1, p2, p3, p4, t))
        WRAP_RAYLIB_FUNC(GetSplinePointBezierQuad, Vector2, (Vector2 p1, Vector2 c2, Vector2 p3, float t), (p1, c2, p3, t))
        WRAP_RAYLIB_FUNC(GetSplinePointBezierCubic, Vector2, (Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float t), (p1, c2, c3, p4, t))
        WRAP_RAYLIB_FUNC(CheckCollisionRecs, bool, (Rectangle rec1, Rectangle rec2), (rec1, rec2))
        WRAP_RAYLIB_FUNC(CheckCollisionCircles, bool, (Vector2 center1, float radius1, Vector2 center2, float radius2), (center1, radius1, center2, radius2))
        WRAP_RAYLIB_FUNC(CheckCollisionCircleRec, bool, (Vector2 center, float radius, Rectangle rec), (center, radius, rec))
        WRAP_RAYLIB_FUNC(CheckCollisionPointRec, bool, (Vector2 point, Rectangle rec), (point, rec))
        WRAP_RAYLIB_FUNC(CheckCollisionPointCircle, bool, (Vector2 point, Vector2 center, float radius), (point, center, radius))
        WRAP_RAYLIB_FUNC(CheckCollisionPointTriangle, bool, (Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3), (point, p1, p2, p3))
        WRAP_RAYLIB_FUNC(CheckCollisionPointPoly, bool, (Vector2 point, const Vector2* points, int pointCount), (point, points, pointCount))
        WRAP_RAYLIB_FUNC(CheckCollisionLines, bool, (Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, Vector2* collisionPoint), (startPos1, endPos1, startPos2, endPos2, collisionPoint))
        WRAP_RAYLIB_FUNC(CheckCollisionPointLine, bool, (Vector2 point, Vector2 p1, Vector2 p2, int threshold), (point, p1, p2, threshold))
        WRAP_RAYLIB_FUNC(CheckCollisionCircleLine, bool, (Vector2 center, float radius, Vector2 p1, Vector2 p2), (center, radius, p1, p2))
        WRAP_RAYLIB_FUNC(GetCollisionRec, Rectangle, (Rectangle rec1, Rectangle rec2), (rec1, rec2))
        WRAP_RAYLIB_FUNC(LoadImage, Image, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadImageRaw, Image, (const char* fileName, int width, int height, int format, int headerSize), (fileName, width, height, format, headerSize))
        WRAP_RAYLIB_FUNC(LoadImageSvg, Image, (const char* fileNameOrString, int width, int height), (fileNameOrString, width, height))
        WRAP_RAYLIB_FUNC(LoadImageAnim, Image, (const char* fileName, int* frames), (fileName, frames))
        WRAP_RAYLIB_FUNC(LoadImageAnimFromMemory, Image, (const char* fileType, const unsigned char* fileData, int dataSize, int* frames), (fileType, fileData, dataSize, frames))
        WRAP_RAYLIB_FUNC(LoadImageFromMemory, Image, (const char* fileType, const unsigned char* fileData, int dataSize), (fileType, fileData, dataSize))
        WRAP_RAYLIB_FUNC(LoadImageFromTexture, Image, (Texture2D texture), (texture))
        WRAP_RAYLIB_FUNC_NO_ARGS(LoadImageFromScreen, Image)
        WRAP_RAYLIB_FUNC(IsImageReady, bool, (Image image), (image))
        WRAP_RAYLIB_FUNC(UnloadImage, void, (Image image), (image))
        WRAP_RAYLIB_FUNC(ExportImage, bool, (Image image, const char* fileName), (image, fileName))
        WRAP_RAYLIB_FUNC(ExportImageAsCode, bool, (Image image, const char* fileName), (image, fileName))
        WRAP_RAYLIB_FUNC(GenImageColor, Image, (int width, int height, Color color), (width, height, color))
        WRAP_RAYLIB_FUNC(GenImageGradientLinear, Image, (int width, int height, int direction, Color start, Color end), (width, height, direction, start, end))
        WRAP_RAYLIB_FUNC(GenImageGradientRadial, Image, (int width, int height, float density, Color inner, Color outer), (width, height, density, inner, outer))
        WRAP_RAYLIB_FUNC(GenImageGradientSquare, Image, (int width, int height, float density, Color inner, Color outer), (width, height, density, inner, outer))
        WRAP_RAYLIB_FUNC(GenImageChecked, Image, (int width, int height, int checksX, int checksY, Color col1, Color col2), (width, height, checksX, checksY, col1, col2))
        WRAP_RAYLIB_FUNC(GenImageWhiteNoise, Image, (int width, int height, float factor), (width, height, factor))
        WRAP_RAYLIB_FUNC(GenImagePerlinNoise, Image, (int width, int height, int offsetX, int offsetY, float scale), (width, height, offsetX, offsetY, scale))
        WRAP_RAYLIB_FUNC(GenImageCellular, Image, (int width, int height, int tileSize), (width, height, tileSize))
        WRAP_RAYLIB_FUNC(GenImageText, Image, (int width, int height, const char* text), (width, height, text))
        WRAP_RAYLIB_FUNC(ImageCopy, Image, (Image image), (image))
        WRAP_RAYLIB_FUNC(ImageFromImage, Image, (Image image, Rectangle rec), (image, rec))
        WRAP_RAYLIB_FUNC(ImageFromChannel, Image, (Image image, int selectedChannel), (image, selectedChannel))
        WRAP_RAYLIB_FUNC(ImageText, Image, (const char* text, int fontSize, Color color), (text, fontSize, color))
        WRAP_RAYLIB_FUNC(ImageTextEx, Image, (Font font, const char* text, float fontSize, float spacing, Color tint), (font, text, fontSize, spacing, tint))
        WRAP_RAYLIB_FUNC(ImageFormat, void, (Image* image, int newFormat), (image, newFormat))
        WRAP_RAYLIB_FUNC(ImageToPOT, void, (Image* image, Color fill), (image, fill))
        WRAP_RAYLIB_FUNC(ImageCrop, void, (Image* image, Rectangle crop), (image, crop))
        WRAP_RAYLIB_FUNC(ImageAlphaCrop, void, (Image* image, float threshold), (image, threshold))
        WRAP_RAYLIB_FUNC(ImageAlphaClear, void, (Image* image, Color color, float threshold), (image, color, threshold))
        WRAP_RAYLIB_FUNC(ImageAlphaMask, void, (Image* image, Image alphaMask), (image, alphaMask))
        WRAP_RAYLIB_FUNC(ImageAlphaPremultiply, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageBlurGaussian, void, (Image* image, int blurSize), (image, blurSize))
        WRAP_RAYLIB_FUNC(ImageKernelConvolution, void, (Image* image, const float* kernel, int kernelSize), (image, kernel, kernelSize))
        WRAP_RAYLIB_FUNC(ImageResize, void, (Image* image, int newWidth, int newHeight), (image, newWidth, newHeight))
        WRAP_RAYLIB_FUNC(ImageResizeNN, void, (Image* image, int newWidth, int newHeight), (image, newWidth, newHeight))
        WRAP_RAYLIB_FUNC(ImageResizeCanvas, void, (Image* image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill), (image, newWidth, newHeight, offsetX, offsetY, fill))
        WRAP_RAYLIB_FUNC(ImageMipmaps, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageDither, void, (Image* image, int rBpp, int gBpp, int bBpp, int aBpp), (image, rBpp, gBpp, bBpp, aBpp))
        WRAP_RAYLIB_FUNC(ImageFlipVertical, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageFlipHorizontal, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageRotate, void, (Image* image, int degrees), (image, degrees))
        WRAP_RAYLIB_FUNC(ImageRotateCW, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageRotateCCW, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageColorTint, void, (Image* image, Color color), (image, color))
        WRAP_RAYLIB_FUNC(ImageColorInvert, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageColorGrayscale, void, (Image* image), (image))
        WRAP_RAYLIB_FUNC(ImageColorContrast, void, (Image* image, float contrast), (image, contrast))
        WRAP_RAYLIB_FUNC(ImageColorBrightness, void, (Image* image, int brightness), (image, brightness))
        WRAP_RAYLIB_FUNC(ImageColorReplace, void, (Image* image, Color color, Color replace), (image, color, replace))
        WRAP_RAYLIB_FUNC(UnloadImageColors, void, (Color* colors), (colors))
        WRAP_RAYLIB_FUNC(UnloadImagePalette, void, (Color* colors), (colors))
        WRAP_RAYLIB_FUNC(GetImageAlphaBorder, Rectangle, (Image image, float threshold), (image, threshold))
        WRAP_RAYLIB_FUNC(GetImageColor, Color, (Image image, int x, int y), (image, x, y))
        WRAP_RAYLIB_FUNC(ImageClearBackground, void, (Image* dst, Color color), (dst, color))
        WRAP_RAYLIB_FUNC(ImageDrawPixel, void, (Image* dst, int posX, int posY, Color color), (dst, posX, posY, color))
        WRAP_RAYLIB_FUNC(ImageDrawPixelV, void, (Image* dst, Vector2 position, Color color), (dst, position, color))
        WRAP_RAYLIB_FUNC(ImageDrawLine, void, (Image* dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color), (dst, startPosX, startPosY, endPosX, endPosY, color))
        WRAP_RAYLIB_FUNC(ImageDrawLineV, void, (Image* dst, Vector2 start, Vector2 end, Color color), (dst, start, end, color))
        WRAP_RAYLIB_FUNC(ImageDrawLineEx, void, (Image* dst, Vector2 start, Vector2 end, int thick, Color color), (dst, start, end, thick, color))
        WRAP_RAYLIB_FUNC(ImageDrawCircle, void, (Image* dst, int centerX, int centerY, int radius, Color color), (dst, centerX, centerY, radius, color))
        WRAP_RAYLIB_FUNC(ImageDrawCircleV, void, (Image* dst, Vector2 center, int radius, Color color), (dst, center, radius, color))
        WRAP_RAYLIB_FUNC(ImageDrawCircleLines, void, (Image* dst, int centerX, int centerY, int radius, Color color), (dst, centerX, centerY, radius, color))
        WRAP_RAYLIB_FUNC(ImageDrawCircleLinesV, void, (Image* dst, Vector2 center, int radius, Color color), (dst, center, radius, color))
        WRAP_RAYLIB_FUNC(ImageDrawRectangle, void, (Image* dst, int posX, int posY, int width, int height, Color color), (dst, posX, posY, width, height, color))
        WRAP_RAYLIB_FUNC(ImageDrawRectangleV, void, (Image* dst, Vector2 position, Vector2 size, Color color), (dst, position, size, color))
        WRAP_RAYLIB_FUNC(ImageDrawRectangleRec, void, (Image* dst, Rectangle rec, Color color), (dst, rec, color))
        WRAP_RAYLIB_FUNC(ImageDrawRectangleLines, void, (Image* dst, Rectangle rec, int thick, Color color), (dst, rec, thick, color))
        WRAP_RAYLIB_FUNC(ImageDrawTriangle, void, (Image* dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color), (dst, v1, v2, v3, color))
        WRAP_RAYLIB_FUNC(ImageDrawTriangleEx, void, (Image* dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3), (dst, v1, v2, v3, c1, c2, c3))
        WRAP_RAYLIB_FUNC(ImageDrawTriangleLines, void, (Image* dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color), (dst, v1, v2, v3, color))
        WRAP_RAYLIB_FUNC(ImageDrawTriangleFan, void, (Image* dst, Vector2* points, int pointCount, Color color), (dst, points, pointCount, color))
        WRAP_RAYLIB_FUNC(ImageDrawTriangleStrip, void, (Image* dst, Vector2* points, int pointCount, Color color), (dst, points, pointCount, color))
        WRAP_RAYLIB_FUNC(ImageDraw, void, (Image* dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint), (dst, src, srcRec, dstRec, tint))
        WRAP_RAYLIB_FUNC(ImageDrawText, void, (Image* dst, const char* text, int posX, int posY, int fontSize, Color color), (dst, text, posX, posY, fontSize, color))
        WRAP_RAYLIB_FUNC(ImageDrawTextEx, void, (Image* dst, Font font, const char* text, Vector2 position, float fontSize, float spacing, Color tint), (dst, font, text, position, fontSize, spacing, tint))
        WRAP_RAYLIB_FUNC(LoadTexture, Texture2D, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadTextureFromImage, Texture2D, (Image image), (image))
        WRAP_RAYLIB_FUNC(LoadTextureCubemap, TextureCubemap, (Image image, int layout), (image, layout))
        WRAP_RAYLIB_FUNC(LoadRenderTexture, RenderTexture2D, (int width, int height), (width, height))
        WRAP_RAYLIB_FUNC(IsTextureReady, bool, (Texture2D texture), (texture))
        WRAP_RAYLIB_FUNC(UnloadTexture, void, (Texture2D texture), (texture))
        WRAP_RAYLIB_FUNC(IsRenderTextureReady, bool, (RenderTexture2D target), (target))
        WRAP_RAYLIB_FUNC(UnloadRenderTexture, void, (RenderTexture2D target), (target))
        WRAP_RAYLIB_FUNC(UpdateTexture, void, (Texture2D texture, const void* pixels), (texture, pixels))
        WRAP_RAYLIB_FUNC(UpdateTextureRec, void, (Texture2D texture, Rectangle rec, const void* pixels), (texture, rec, pixels))
        WRAP_RAYLIB_FUNC(GenTextureMipmaps, void, (Texture2D* texture), (texture))
        WRAP_RAYLIB_FUNC(SetTextureFilter, void, (Texture2D texture, int filter), (texture, filter))
        WRAP_RAYLIB_FUNC(SetTextureWrap, void, (Texture2D texture, int wrap), (texture, wrap))
        WRAP_RAYLIB_FUNC(DrawTexture, void, (Texture2D texture, int posX, int posY, Color tint), (texture, posX, posY, tint))
        WRAP_RAYLIB_FUNC(DrawTextureV, void, (Texture2D texture, Vector2 position, Color tint), (texture, position, tint))
        WRAP_RAYLIB_FUNC(DrawTextureEx, void, (Texture2D texture, Vector2 position, float rotation, float scale, Color tint), (texture, position, rotation, scale, tint))
        WRAP_RAYLIB_FUNC(DrawTextureRec, void, (Texture2D texture, Rectangle source, Vector2 position, Color tint), (texture, source, position, tint))
        WRAP_RAYLIB_FUNC(DrawTexturePro, void, (Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint), (texture, source, dest, origin, rotation, tint))
        WRAP_RAYLIB_FUNC(DrawTextureNPatch, void, (Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, float rotation, Color tint), (texture, nPatchInfo, dest, origin, rotation, tint))
        WRAP_RAYLIB_FUNC(ColorIsEqual, bool, (Color col1, Color col2), (col1, col2))
        WRAP_RAYLIB_FUNC(Fade, Color, (Color color, float alpha), (color, alpha))
        WRAP_RAYLIB_FUNC(ColorToInt, int, (Color color), (color))
        WRAP_RAYLIB_FUNC(ColorNormalize, Vector4, (Color color), (color))
        WRAP_RAYLIB_FUNC(ColorFromNormalized, Color, (Vector4 normalized), (normalized))
        WRAP_RAYLIB_FUNC(ColorToHSV, Vector3, (Color color), (color))
        WRAP_RAYLIB_FUNC(ColorFromHSV, Color, (float hue, float saturation, float value), (hue, saturation, value))
        WRAP_RAYLIB_FUNC(ColorTint, Color, (Color color, Color tint), (color, tint))
        WRAP_RAYLIB_FUNC(ColorBrightness, Color, (Color color, float factor), (color, factor))
        WRAP_RAYLIB_FUNC(ColorContrast, Color, (Color color, float contrast), (color, contrast))
        WRAP_RAYLIB_FUNC(ColorAlpha, Color, (Color color, float alpha), (color, alpha))
        WRAP_RAYLIB_FUNC(ColorAlphaBlend, Color, (Color dst, Color src, Color tint), (dst, src, tint))
        WRAP_RAYLIB_FUNC(ColorLerp, Color, (Color color1, Color color2, float factor), (color1, color2, factor))
        WRAP_RAYLIB_FUNC(GetColor, Color, (unsigned int hexValue), (hexValue))
        WRAP_RAYLIB_FUNC(GetPixelColor, Color, (void* srcPtr, int format), (srcPtr, format))
        WRAP_RAYLIB_FUNC(SetPixelColor, void, (void* dstPtr, Color color, int format), (dstPtr, color, format))
        WRAP_RAYLIB_FUNC(GetPixelDataSize, int, (int width, int height, int format), (width, height, format))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetFontDefault, Font)
        WRAP_RAYLIB_FUNC(LoadFont, Font, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadFontEx, Font, (const char* fileName, int fontSize, int* codepoints, int codepointCount), (fileName, fontSize, codepoints, codepointCount))
        WRAP_RAYLIB_FUNC(LoadFontFromImage, Font, (Image image, Color key, int firstChar), (image, key, firstChar))
        WRAP_RAYLIB_FUNC(LoadFontFromMemory, Font, (const char* fileType, const unsigned char* fileData, int dataSize, int fontSize, int* codepoints, int codepointCount), (fileType, fileData, dataSize, fontSize, codepoints, codepointCount))
        WRAP_RAYLIB_FUNC(IsFontReady, bool, (Font font), (font))
        WRAP_RAYLIB_FUNC(GenImageFontAtlas, Image, (const GlyphInfo* glyphs, Rectangle** glyphRecs, int glyphCount, int fontSize, int padding, int packMethod), (glyphs, glyphRecs, glyphCount, fontSize, padding, packMethod))
        WRAP_RAYLIB_FUNC(UnloadFontData, void, (GlyphInfo* glyphs, int glyphCount), (glyphs, glyphCount))
        WRAP_RAYLIB_FUNC(UnloadFont, void, (Font font), (font))
        WRAP_RAYLIB_FUNC(ExportFontAsCode, bool, (Font font, const char* fileName), (font, fileName))
        WRAP_RAYLIB_FUNC(DrawFPS, void, (int posX, int posY), (posX, posY))
        WRAP_RAYLIB_FUNC(DrawText, void, (const char* text, int posX, int posY, int fontSize, Color color), (text, posX, posY, fontSize, color))
        WRAP_RAYLIB_FUNC(DrawTextEx, void, (Font font, const char* text, Vector2 position, float fontSize, float spacing, Color tint), (font, text, position, fontSize, spacing, tint))
        WRAP_RAYLIB_FUNC(DrawTextPro, void, (Font font, const char* text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint), (font, text, position, origin, rotation, fontSize, spacing, tint))
        WRAP_RAYLIB_FUNC(DrawTextCodepoint, void, (Font font, int codepoint, Vector2 position, float fontSize, Color tint), (font, codepoint, position, fontSize, tint))
        WRAP_RAYLIB_FUNC(DrawTextCodepoints, void, (Font font, const int* codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint), (font, codepoints, codepointCount, position, fontSize, spacing, tint))
        WRAP_RAYLIB_FUNC(SetTextLineSpacing, void, (int spacing), (spacing))
        WRAP_RAYLIB_FUNC(MeasureText, int, (const char* text, int fontSize), (text, fontSize))
        WRAP_RAYLIB_FUNC(MeasureTextEx, Vector2, (Font font, const char* text, float fontSize, float spacing), (font, text, fontSize, spacing))
        WRAP_RAYLIB_FUNC(GetGlyphIndex, int, (Font font, int codepoint), (font, codepoint))
        WRAP_RAYLIB_FUNC(GetGlyphInfo, GlyphInfo, (Font font, int codepoint), (font, codepoint))
        WRAP_RAYLIB_FUNC(GetGlyphAtlasRec, Rectangle, (Font font, int codepoint), (font, codepoint))
        WRAP_RAYLIB_FUNC(UnloadUTF8, void, (char* text), (text))
        WRAP_RAYLIB_FUNC(UnloadCodepoints, void, (int* codepoints), (codepoints))
        WRAP_RAYLIB_FUNC(GetCodepointCount, int, (const char* text), (text))
        WRAP_RAYLIB_FUNC(GetCodepoint, int, (const char* text, int* codepointSize), (text, codepointSize))
        WRAP_RAYLIB_FUNC(GetCodepointNext, int, (const char* text, int* codepointSize), (text, codepointSize))
        WRAP_RAYLIB_FUNC(GetCodepointPrevious, int, (const char* text, int* codepointSize), (text, codepointSize))
        WRAP_RAYLIB_FUNC(TextCopy, int, (char* dst, const char* src), (dst, src))
        WRAP_RAYLIB_FUNC(TextIsEqual, bool, (const char* text1, const char* text2), (text1, text2))
        WRAP_RAYLIB_FUNC(TextAppend, void, (char* text, const char* append, int* position), (text, append, position))
        WRAP_RAYLIB_FUNC(TextFindIndex, int, (const char* text, const char* find), (text, find))
        WRAP_RAYLIB_FUNC(TextToInteger, int, (const char* text), (text))
        WRAP_RAYLIB_FUNC(TextToFloat, float, (const char* text), (text))
        WRAP_RAYLIB_FUNC(DrawLine3D, void, (Vector3 startPos, Vector3 endPos, Color color), (startPos, endPos, color))
        WRAP_RAYLIB_FUNC(DrawPoint3D, void, (Vector3 position, Color color), (position, color))
        WRAP_RAYLIB_FUNC(DrawCircle3D, void, (Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color), (center, radius, rotationAxis, rotationAngle, color))
        WRAP_RAYLIB_FUNC(DrawTriangle3D, void, (Vector3 v1, Vector3 v2, Vector3 v3, Color color), (v1, v2, v3, color))
        WRAP_RAYLIB_FUNC(DrawTriangleStrip3D, void, (const Vector3* points, int pointCount, Color color), (points, pointCount, color))
        WRAP_RAYLIB_FUNC(DrawCube, void, (Vector3 position, float width, float height, float length, Color color), (position, width, height, length, color))
        WRAP_RAYLIB_FUNC(DrawCubeV, void, (Vector3 position, Vector3 size, Color color), (position, size, color))
        WRAP_RAYLIB_FUNC(DrawCubeWires, void, (Vector3 position, float width, float height, float length, Color color), (position, width, height, length, color))
        WRAP_RAYLIB_FUNC(DrawCubeWiresV, void, (Vector3 position, Vector3 size, Color color), (position, size, color))
        WRAP_RAYLIB_FUNC(DrawSphere, void, (Vector3 centerPos, float radius, Color color), (centerPos, radius, color))
        WRAP_RAYLIB_FUNC(DrawSphereEx, void, (Vector3 centerPos, float radius, int rings, int slices, Color color), (centerPos, radius, rings, slices, color))
        WRAP_RAYLIB_FUNC(DrawSphereWires, void, (Vector3 centerPos, float radius, int rings, int slices, Color color), (centerPos, radius, rings, slices, color))
        WRAP_RAYLIB_FUNC(DrawCylinder, void, (Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color), (position, radiusTop, radiusBottom, height, slices, color))
        WRAP_RAYLIB_FUNC(DrawCylinderEx, void, (Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color), (startPos, endPos, startRadius, endRadius, sides, color))
        WRAP_RAYLIB_FUNC(DrawCylinderWires, void, (Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color), (position, radiusTop, radiusBottom, height, slices, color))
        WRAP_RAYLIB_FUNC(DrawCylinderWiresEx, void, (Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color), (startPos, endPos, startRadius, endRadius, sides, color))
        WRAP_RAYLIB_FUNC(DrawCapsule, void, (Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color), (startPos, endPos, radius, slices, rings, color))
        WRAP_RAYLIB_FUNC(DrawCapsuleWires, void, (Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color), (startPos, endPos, radius, slices, rings, color))
        WRAP_RAYLIB_FUNC(DrawPlane, void, (Vector3 centerPos, Vector2 size, Color color), (centerPos, size, color))
        WRAP_RAYLIB_FUNC(DrawRay, void, (Ray ray, Color color), (ray, color))
        WRAP_RAYLIB_FUNC(DrawGrid, void, (int slices, float spacing), (slices, spacing))
        WRAP_RAYLIB_FUNC(LoadModel, Model, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadModelFromMesh, Model, (Mesh mesh), (mesh))
        WRAP_RAYLIB_FUNC(IsModelReady, bool, (Model model), (model))
        WRAP_RAYLIB_FUNC(UnloadModel, void, (Model model), (model))
        WRAP_RAYLIB_FUNC(GetModelBoundingBox, BoundingBox, (Model model), (model))
        WRAP_RAYLIB_FUNC(DrawModel, void, (Model model, Vector3 position, float scale, Color tint), (model, position, scale, tint))
        WRAP_RAYLIB_FUNC(DrawModelEx, void, (Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint), (model, position, rotationAxis, rotationAngle, scale, tint))
        WRAP_RAYLIB_FUNC(DrawModelWires, void, (Model model, Vector3 position, float scale, Color tint), (model, position, scale, tint))
        WRAP_RAYLIB_FUNC(DrawModelWiresEx, void, (Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint), (model, position, rotationAxis, rotationAngle, scale, tint))
        WRAP_RAYLIB_FUNC(DrawModelPoints, void, (Model model, Vector3 position, float scale, Color tint), (model, position, scale, tint))
        WRAP_RAYLIB_FUNC(DrawModelPointsEx, void, (Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint), (model, position, rotationAxis, rotationAngle, scale, tint))
        WRAP_RAYLIB_FUNC(DrawBoundingBox, void, (BoundingBox box, Color color), (box, color))
        WRAP_RAYLIB_FUNC(DrawBillboard, void, (Camera camera, Texture2D texture, Vector3 position, float scale, Color tint), (camera, texture, position, scale, tint))
        WRAP_RAYLIB_FUNC(DrawBillboardRec, void, (Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector2 size, Color tint), (camera, texture, source, position, size, tint))
        WRAP_RAYLIB_FUNC(DrawBillboardPro, void, (Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint), (camera, texture, source, position, up, size, origin, rotation, tint))
        WRAP_RAYLIB_FUNC(UploadMesh, void, (Mesh* mesh, bool dynamic), (mesh, dynamic))
        WRAP_RAYLIB_FUNC(UpdateMeshBuffer, void, (Mesh mesh, int index, const void* data, int dataSize, int offset), (mesh, index, data, dataSize, offset))
        WRAP_RAYLIB_FUNC(UnloadMesh, void, (Mesh mesh), (mesh))
        WRAP_RAYLIB_FUNC(DrawMesh, void, (Mesh mesh, Material material, Matrix transform), (mesh, material, transform))
        WRAP_RAYLIB_FUNC(DrawMeshInstanced, void, (Mesh mesh, Material material, const Matrix* transforms, int instances), (mesh, material, transforms, instances))
        WRAP_RAYLIB_FUNC(GetMeshBoundingBox, BoundingBox, (Mesh mesh), (mesh))
        WRAP_RAYLIB_FUNC(GenMeshTangents, void, (Mesh* mesh), (mesh))
        WRAP_RAYLIB_FUNC(ExportMesh, bool, (Mesh mesh, const char* fileName), (mesh, fileName))
        WRAP_RAYLIB_FUNC(ExportMeshAsCode, bool, (Mesh mesh, const char* fileName), (mesh, fileName))
        WRAP_RAYLIB_FUNC(GenMeshPoly, Mesh, (int sides, float radius), (sides, radius))
        WRAP_RAYLIB_FUNC(GenMeshPlane, Mesh, (float width, float length, int resX, int resZ), (width, length, resX, resZ))
        WRAP_RAYLIB_FUNC(GenMeshCube, Mesh, (float width, float height, float length), (width, height, length))
        WRAP_RAYLIB_FUNC(GenMeshSphere, Mesh, (float radius, int rings, int slices), (radius, rings, slices))
        WRAP_RAYLIB_FUNC(GenMeshHemiSphere, Mesh, (float radius, int rings, int slices), (radius, rings, slices))
        WRAP_RAYLIB_FUNC(GenMeshCylinder, Mesh, (float radius, float height, int slices), (radius, height, slices))
        WRAP_RAYLIB_FUNC(GenMeshCone, Mesh, (float radius, float height, int slices), (radius, height, slices))
        WRAP_RAYLIB_FUNC(GenMeshTorus, Mesh, (float radius, float size, int radSeg, int sides), (radius, size, radSeg, sides))
        WRAP_RAYLIB_FUNC(GenMeshKnot, Mesh, (float radius, float size, int radSeg, int sides), (radius, size, radSeg, sides))
        WRAP_RAYLIB_FUNC(GenMeshHeightmap, Mesh, (Image heightmap, Vector3 size), (heightmap, size))
        WRAP_RAYLIB_FUNC(GenMeshCubicmap, Mesh, (Image cubicmap, Vector3 cubeSize), (cubicmap, cubeSize))
        WRAP_RAYLIB_FUNC_NO_ARGS(LoadMaterialDefault, Material)
        WRAP_RAYLIB_FUNC(IsMaterialReady, bool, (Material material), (material))
        WRAP_RAYLIB_FUNC(UnloadMaterial, void, (Material material), (material))
        WRAP_RAYLIB_FUNC(SetMaterialTexture, void, (Material* material, int mapType, Texture2D texture), (material, mapType, texture))
        WRAP_RAYLIB_FUNC(SetModelMeshMaterial, void, (Model* model, int meshId, int materialId), (model, meshId, materialId))
        WRAP_RAYLIB_FUNC(UpdateModelAnimation, void, (Model model, ModelAnimation anim, int frame), (model, anim, frame))
        WRAP_RAYLIB_FUNC(UnloadModelAnimation, void, (ModelAnimation anim), (anim))
        WRAP_RAYLIB_FUNC(UnloadModelAnimations, void, (ModelAnimation* animations, int animCount), (animations, animCount))
        WRAP_RAYLIB_FUNC(IsModelAnimationValid, bool, (Model model, ModelAnimation anim), (model, anim))
        WRAP_RAYLIB_FUNC(CheckCollisionSpheres, bool, (Vector3 center1, float radius1, Vector3 center2, float radius2), (center1, radius1, center2, radius2))
        WRAP_RAYLIB_FUNC(CheckCollisionBoxes, bool, (BoundingBox box1, BoundingBox box2), (box1, box2))
        WRAP_RAYLIB_FUNC(CheckCollisionBoxSphere, bool, (BoundingBox box, Vector3 center, float radius), (box, center, radius))
        WRAP_RAYLIB_FUNC(GetRayCollisionSphere, RayCollision, (Ray ray, Vector3 center, float radius), (ray, center, radius))
        WRAP_RAYLIB_FUNC(GetRayCollisionBox, RayCollision, (Ray ray, BoundingBox box), (ray, box))
        WRAP_RAYLIB_FUNC(GetRayCollisionMesh, RayCollision, (Ray ray, Mesh mesh, Matrix transform), (ray, mesh, transform))
        WRAP_RAYLIB_FUNC(GetRayCollisionTriangle, RayCollision, (Ray ray, Vector3 p1, Vector3 p2, Vector3 p3), (ray, p1, p2, p3))
        WRAP_RAYLIB_FUNC(GetRayCollisionQuad, RayCollision, (Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4), (ray, p1, p2, p3, p4))
        WRAP_RAYLIB_FUNC_NO_ARGS(InitAudioDevice, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(CloseAudioDevice, void)
        WRAP_RAYLIB_FUNC_NO_ARGS(IsAudioDeviceReady, bool)
        WRAP_RAYLIB_FUNC(SetMasterVolume, void, (float volume), (volume))
        WRAP_RAYLIB_FUNC_NO_ARGS(GetMasterVolume, float)
        WRAP_RAYLIB_FUNC(LoadWave, Wave, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadWaveFromMemory, Wave, (const char* fileType, const unsigned char* fileData, int dataSize), (fileType, fileData, dataSize))
        WRAP_RAYLIB_FUNC(IsWaveReady, bool, (Wave wave), (wave))
        WRAP_RAYLIB_FUNC(LoadSound, Sound, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadSoundFromWave, Sound, (Wave wave), (wave))
        WRAP_RAYLIB_FUNC(LoadSoundAlias, Sound, (Sound source), (source))
        WRAP_RAYLIB_FUNC(IsSoundReady, bool, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(UpdateSound, void, (Sound sound, const void* data, int sampleCount), (sound, data, sampleCount))
        WRAP_RAYLIB_FUNC(UnloadWave, void, (Wave wave), (wave))
        WRAP_RAYLIB_FUNC(UnloadSound, void, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(UnloadSoundAlias, void, (Sound alias), (alias))
        WRAP_RAYLIB_FUNC(ExportWave, bool, (Wave wave, const char* fileName), (wave, fileName))
        WRAP_RAYLIB_FUNC(ExportWaveAsCode, bool, (Wave wave, const char* fileName), (wave, fileName))
        WRAP_RAYLIB_FUNC(PlaySound, void, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(StopSound, void, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(PauseSound, void, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(ResumeSound, void, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(IsSoundPlaying, bool, (Sound sound), (sound))
        WRAP_RAYLIB_FUNC(SetSoundVolume, void, (Sound sound, float volume), (sound, volume))
        WRAP_RAYLIB_FUNC(SetSoundPitch, void, (Sound sound, float pitch), (sound, pitch))
        WRAP_RAYLIB_FUNC(SetSoundPan, void, (Sound sound, float pan), (sound, pan))
        WRAP_RAYLIB_FUNC(WaveCopy, Wave, (Wave wave), (wave))
        WRAP_RAYLIB_FUNC(WaveCrop, void, (Wave* wave, int initFrame, int finalFrame), (wave, initFrame, finalFrame))
        WRAP_RAYLIB_FUNC(WaveFormat, void, (Wave* wave, int sampleRate, int sampleSize, int channels), (wave, sampleRate, sampleSize, channels))
        WRAP_RAYLIB_FUNC(UnloadWaveSamples, void, (float* samples), (samples))
        WRAP_RAYLIB_FUNC(LoadMusicStream, Music, (const char* fileName), (fileName))
        WRAP_RAYLIB_FUNC(LoadMusicStreamFromMemory, Music, (const char* fileType, const unsigned char* data, int dataSize), (fileType, data, dataSize))
        WRAP_RAYLIB_FUNC(IsMusicReady, bool, (Music music), (music))
        WRAP_RAYLIB_FUNC(UnloadMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(PlayMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(IsMusicStreamPlaying, bool, (Music music), (music))
        WRAP_RAYLIB_FUNC(UpdateMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(StopMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(PauseMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(ResumeMusicStream, void, (Music music), (music))
        WRAP_RAYLIB_FUNC(SeekMusicStream, void, (Music music, float position), (music, position))
        WRAP_RAYLIB_FUNC(SetMusicVolume, void, (Music music, float volume), (music, volume))
        WRAP_RAYLIB_FUNC(SetMusicPitch, void, (Music music, float pitch), (music, pitch))
        WRAP_RAYLIB_FUNC(SetMusicPan, void, (Music music, float pan), (music, pan))
        WRAP_RAYLIB_FUNC(GetMusicTimeLength, float, (Music music), (music))
        WRAP_RAYLIB_FUNC(GetMusicTimePlayed, float, (Music music), (music))
        WRAP_RAYLIB_FUNC(LoadAudioStream, AudioStream, (unsigned int sampleRate, unsigned int sampleSize, unsigned int channels), (sampleRate, sampleSize, channels))
        WRAP_RAYLIB_FUNC(IsAudioStreamReady, bool, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(UnloadAudioStream, void, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(UpdateAudioStream, void, (AudioStream stream, const void* data, int frameCount), (stream, data, frameCount))
        WRAP_RAYLIB_FUNC(IsAudioStreamProcessed, bool, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(PlayAudioStream, void, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(PauseAudioStream, void, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(ResumeAudioStream, void, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(IsAudioStreamPlaying, bool, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(StopAudioStream, void, (AudioStream stream), (stream))
        WRAP_RAYLIB_FUNC(SetAudioStreamVolume, void, (AudioStream stream, float volume), (stream, volume))
        WRAP_RAYLIB_FUNC(SetAudioStreamPitch, void, (AudioStream stream, float pitch), (stream, pitch))
        WRAP_RAYLIB_FUNC(SetAudioStreamPan, void, (AudioStream stream, float pan), (stream, pan))
        WRAP_RAYLIB_FUNC(SetAudioStreamBufferSizeDefault, void, (int size), (size))
        WRAP_RAYLIB_FUNC(SetAudioStreamCallback, void, (AudioStream stream, AudioCallback callback), (stream, callback))
        WRAP_RAYLIB_FUNC(AttachAudioStreamProcessor, void, (AudioStream stream, AudioCallback processor), (stream, processor))
        WRAP_RAYLIB_FUNC(DetachAudioStreamProcessor, void, (AudioStream stream, AudioCallback processor), (stream, processor))
        WRAP_RAYLIB_FUNC(AttachAudioMixedProcessor, void, (AudioCallback processor), (processor))
        WRAP_RAYLIB_FUNC(DetachAudioMixedProcessor, void, (AudioCallback processor), (processor))

#pragma endregion
}

#pragma managed(pop)